version: "2"
services:
  server:
    container_name: node
    build: .
    ports:
      - 8000:8000
      - 9229:9229 #debugger port   
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres@postgres/betheherots
      PORT: 8000
      REDIS_URL: redis://redis:6379
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: betheherots
      POSTGRES_HOST_AUTH_METHOD: trust      

  redis:
    container_name: redis
    image: redis:7.0.13-alpine

  nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:            
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        

  certbot:
    container_name: certbot 
    image: certbot/certbot
    depends_on:
            - nginx
    volumes:
      - ./letsencrypt:/etc/letsencrypt    
    command: ["certonly", "--nginx", "-d", "betheherots.com"]
